/nav2/lifecycle_manager:
  ros__parameters:
    /bond_disable_heartbeat_timeout: false
    attempt_respawn_reconnection: true
    autostart: true
    bond_respawn_max_duration: 10.0
    bond_timeout: 4.0
    diagnostic_updater:
      period: 1.0
    node_names: # ORDER MATTERS! Make sure map_server is first, then amcl
    - map_server
    - /nav2/amcl
    - planner_server
    - controller_server
    - behavior_server
    - bt_navigator
    