/nav2/map_server:
  ros__parameters:
    /bond_disable_heartbeat_timeout: true
    frame_id: map
    topic_name: map
    yaml_filename: /home/humble_ws/src/linorobot2_navigation/maps/greenhouse2.yaml

/nav2/lifecycle_manager:
  ros__parameters:
    /bond_disable_heartbeat_timeout: false
    attempt_respawn_reconnection: true
    autostart: true
    bond_respawn_max_duration: 10.0
    bond_timeout: 4.0
    diagnostic_updater:
      period: 1.0
    node_names:
    - map_server    